// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SP.ResourceService.DB;

#nullable disable

namespace SP.ResourceService.Migrations
{
    [DbContext(typeof(ResourceServiceDbContext))]
    [Migration("20250916091411_InitImageText")]
    partial class InitImageText
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SP.ResourceService.Models.Entity.Files", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("Id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("datetime")
                        .HasComment("创建时间");

                    b.Property<long>("CreateUserId")
                        .HasColumnType("bigint")
                        .HasComment("创建用户");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ObjectName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdateDateTime")
                        .HasColumnType("datetime")
                        .HasComment("修改时间");

                    b.Property<long?>("UpdateUserId")
                        .HasColumnType("bigint")
                        .HasComment("修改用户");

                    b.HasKey("Id");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("SP.ResourceService.Models.Entity.ImageText", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("Id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("datetime")
                        .HasComment("创建时间");

                    b.Property<long>("CreateUserId")
                        .HasColumnType("bigint")
                        .HasComment("创建用户");

                    b.Property<long>("FileId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("RecognizedText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdateDateTime")
                        .HasColumnType("datetime")
                        .HasComment("修改时间");

                    b.Property<long?>("UpdateUserId")
                        .HasColumnType("bigint")
                        .HasComment("修改用户");

                    b.HasKey("Id");

                    b.ToTable("image_text");
                });
#pragma warning restore 612, 618
        }
    }
}
