// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SP.CurrencyService.DB;

#nullable disable

namespace SP.CurrencyService.Migrations
{
    [DbContext(typeof(CurrencyServiceDbContext))]
    [Migration("20250619162058_initExchangeRateRecord")]
    partial class initExchangeRateRecord
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SP.CurrencyService.Models.Entity.ExchangeRateRecord", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(36)")
                        .HasComment("Id");

                    b.Property<string>("ConvertCurrency")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasComment("币种转换");

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("datetime")
                        .HasComment("创建时间");

                    b.Property<string>("CreateUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(36)")
                        .HasComment("创建用户");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date")
                        .HasComment("汇率日期");

                    b.Property<decimal>("ExchangeRate")
                        .HasColumnType("decimal(10,2)")
                        .HasComment("汇率");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("UpdateDateTime")
                        .HasColumnType("datetime")
                        .HasComment("修改时间");

                    b.Property<string>("UpdateUserId")
                        .HasColumnType("nvarchar(36)")
                        .HasComment("修改用户");

                    b.HasKey("Id");

                    b.ToTable("ExchangeRateRecords", t =>
                        {
                            t.HasComment("汇率记录");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
