name: Deploy Gateway

on:
  push:
    branches: [ Microservices ]
    paths:
      - 'SP.Gateway/**'
  workflow_dispatch:
    inputs:
      environment:
        description: '部署环境'
        required: true
        default: 'Development'
        type: choice
        options:
          - Development
          - Production
      tag:
        description: 'Docker 镜像标签'
        required: false
        default: 'latest'
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./SP.Gateway/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/sp-gateway:${{ github.event.inputs.tag || 'latest' }}

      - name: Set deployment environment
        run: |
          if [ "${{ github.event_name }}" == "push" ]; then
            echo "ENVIRONMENT=Development" >> $GITHUB_ENV
          else
            echo "ENVIRONMENT=${{ github.event.inputs.environment }}" >> $GITHUB_ENV
          fi

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/sp-gateway:${{ github.event.inputs.tag || 'latest' }}
            docker stop sp-gateway || true
            docker rm sp-gateway || true
            docker run -d --name sp-gateway -p 8977:80 -e ASPNETCORE_ENVIRONMENT=${{ env.ENVIRONMENT }} ${{ secrets.DOCKER_USERNAME }}/sp-gateway:${{ github.event.inputs.tag || 'latest' }}
